### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by lazyDefender** [lazyDefender/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by roman-ortynskyi** [comment]
- Linkedin [linkedin.com/in/roman-ortynskyi-2719b8204](url)
- Email [ortynsky1@gmail.com](url)
- Instagram [instagram.com/rroman_ortynsky](url)
